<?php
	$align_class = '';
	if(isset($align)){
		if($align === 'center')
			$align_class = ' justify-content-center';
		elseif($align === 'right')
			$align_class = ' justify-content-end';
	}
?>
<nav aria-label="Pagination">
    <ul class="pagination<?= $align_class ?>">
        <?php foreach($pages as $page): ?>
            <?php if($page->active): ?>
                <?php if($page->next_btn || $page->prev_btn): ?>
                    <li class="page-item disabled">
                        <a class="page-link" href="#0" tabindex="-1" aria-disabled="true"><?= $page->label ?></a>
                    </li>
                <?php else: ?>
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#0">
                            <?= $page->label ?> <span class="sr-only">(current)</span>
                        </a>
                    </li>
                <?php endif; ?>
            <?php else: ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $page->link ?>">
                        <?= $page->label ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</nav>