<?php
    $value = (string)$value;
    $attrs = [
        'type'        => 'password',
        'class'       => 'form-control',
        'placeholder' => $field->label,
        'id'          => $id,
        'name'        => $field->name
    ];

    $with_meter = false;

    if(isset($field->meter) && $field->meter){
        $with_meter = true;
        $attrs['class'].= ' password-strength';
    }

    if(isset($rules->required) && $rules->required)
        $attrs['required'] = null;
    if(isset($rules->empty) && !$rules->empty)
        $attrs['required'] = null;
    if(isset($rules->length)){
        if(isset($rules->length->min))
            $attrs['minlength'] = $rules->length->min;
        if(isset($rules->length->max))
            $attrs['maxlength'] = $rules->length->max;
    }
?>
<div class="form-group<?= ($error ? ' is-invalid' : '' ) ?>">
    <?php if($show_label): ?>
        <label for="<?= $id ?>"><?= $field->label ?></label>
    <?php endif; ?>
    <?php if($with_meter): ?>
    <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <?php endif; ?>
    <input<?= to_attr($attrs) ?>>
    <div class="invalid-feedback"><?= ($error?$error->text:'') ?></div>
</div>