<?php
    $i_attrs = [
        'name'  => $field->name,
        'class' => 'formimage-model',
        'id'    => $id,
        'value' => ($value??'')
    ];
    // if(isset($rules->required) && $rules->required)
    //     $i_attrs['required'] = null;
    // if(isset($rules->empty) && !$rules->empty)
    //     $i_attrs['required'] = null;

    $c_attrs = [
        'class' => 'formimage',
        'id'    => $id . '-container',
        'data-model' => '#' . $id
    ];
    if(!$value)
        $c_attrs['class'].= ' empty';

    $upload_form = null;
    if(isset($field->form))
        $upload_form = $field->form;
    elseif(isset($rules->upload) && is_string($rules->upload))
        $upload_form = $rules->upload;
    
    if($upload_form)
        $c_attrs['data-form'] = $upload_form;

    $p_attrs = [
        'class'  => 'formimage-preview',
        'target' => '_blank'
    ];
    if($value){
        $p_attrs['href']  = $value;
        $p_attrs['style'] = 'background-image:url('.hs($value).')';
    }
?>
<div class="form-group <?= ($error ? ' is-invalid' : '' ) ?>">
    <?php if($show_label): ?>
        <label for="<?= $id ?>"><?= $field->label ?></label>
    <?php endif; ?>
    <input<?= to_attr($i_attrs) ?>>
    <div<?= to_attr($c_attrs) ?>>
        <button type="button" class="close formimage-clear" aria-label="Close" title="Clear">
            <span aria-hidden="true">×</span>
        </button>
        <a<?= to_attr($p_attrs) ?>>
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="#CCC" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-image">
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
                <circle cx="8.5" cy="8.5" r="1.5"></circle>
                <polyline points="21 15 16 10 5 21"></polyline>
            </svg>
        </a>
    </div>
    <div class="invalid-feedback"><?= ($error?$error->text:'') ?></div>
</div>